### ISSUE TITLE
希望有如下几个修改：dump到json时使用中文名称（而非id），使用GZ的最高等级压缩蓝图，以及，可选的取整运算 

### ISSUE THREAD

**Issue by Neutron3529** [cying314/edit-dspblue-print#2]
我不确定你更喜欢github还是gitee，就两者都发issue了，如果你不喜欢，可以直接删issue

---

这几天我一直在跟外国网友一起改善dspbp，发现了这几个可以改进的地方
一个是dump的时候未必非要以数字形式dump掉id，也可以以字符串形式dump物品名(id)，这样可以同时方便人类阅读，与机器识别（先看能不能直接parse成id，再看最后一个括号是不是id）
一个是，游戏蓝图的GZ压缩等级并不是最高的（我不确定这个程序有没有注意到这一点（因为我对js不太熟），但至少dspbp没有，dspbp只用了default（也就是level 6）），这大概会让蓝图文件大小增加一些
[根据网上搜的测试](https://gitee.com/link?target=https%3A%2F%2Fblog.csdn.net%2Fzdhsoft%2Farticle%2Fdetails%2F122467706)，gz的解压速度与压缩等级无关，也就是说我们可以用GZ的最高等级压缩蓝图。

最后就是可选的蓝图取整了
坐标取整到0.05，yew取整到3（好像我看到过游戏里面有一个向3的整数倍取整的操作，所以用3或许会好一点）可以显著减少蓝图体积（但对某些特殊坐标蓝图，如此取整会导致蓝图不可用）
取整的原理是，游戏会对蓝图做GZ压缩，而带误差的float很难被正确地压缩成功。
实测取整之后蓝图体积减小1/3
rar源文件360k
GZ开level 9+取整之后打包tar380k
7z把380k的蓝图包压缩之后得到的新包只剩下241k了
提升肉眼可见

**Comment by cying314** [comment]
[已在gitee回复](https://gitee.com/cying314/edit-dspblue-print/issues/I8QPUJ#note_23969015_link)
